service: serverless-security

frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  memorySize: 128
  versionFunctions: false

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  alert:
    handler: bin/main
    environment:
      INCOMING_WEBHOOK_URL: ${env:SLACK_INCOMING_WEBHOOK_URL}
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws:securityhub'
            detail-type:
              - 'Security Hub Findings - Imported'
            detail:
              findings:
                Severity:
                  Label:
                    - 'CRITICAL'
                    - 'HIGH'
                    - 'MEDIUM'
