service: example

frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  memorySize: 128
  versionFunctions: false

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  logger:
    handler: bin/main